apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ishikash/my-firstrepo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      env: qa
  template:
    metadata:
      labels:
        app: web
        env: qa
    spec:
      containers:
      - name: web1
        image: nginx:alpine
        ports:
        - containerPort: 80